personal:
  name: "Vaibhav Solanki"
  title: "Senior Software Engineer"
  company: "Postman"
  location: "Bangalore, India"
  email: "vbhvsolanki7500@gmail.com"
  github: "https://github.com/VAIBHAV7500"
  linkedin: "https://linkedin.com/in/vaibhav.solanki"
  #twitter: "https://twitter.com/vaibhavsolanki"
  instagram: "https://www.instagram.com/vbhvsolanki"
  avatar: "/avatar.jpg"
  images:
    - src: "/personal/photo1.png"
      caption: "Working on exciting projects at Postman"
    - src: "/personal/photo2.png"
      caption: "Speaking at developer conferences"
    - src: "/personal/photo3.png"
      caption: "Collaborating with amazing teams"

about:
  summary: "I'm a Senior Software Engineer with 5+ years of experience building scalable web applications and developer tools. Currently working at Postman, I've previously contributed to platforms like HackerRank and BrowserStack."
  description: "Hello there 👋\n\nHappy to see you here!\nI am Vaibhav, a Software Engineer with a passion for building innovative products. My journey in technology is fueled by a love for problem-solving and creating impactful solutions. Beyond coding, I am a big fan of anime and manga, which inspire my creativity. I also love traveling and exploring new places, as each adventure enriches my perspective and fuels my passion for discovery.\n Have a nice day!\n\nBest Vaibhav"
  skills:
    - name: "Golang"
      category: "Language"
      rating: 5
    - name: "Python"
      category: "Language"
      rating: 5
    - name: "JavaScript"
      category: "Language"
      rating: 5
    - name: "TypeScript"
      category: "Language"
      rating: 4
    - name: "SQL"
      category: "Language"
      rating: 4
    - name: "React"
      category: "Framework"
      rating: 5
    - name: "Node.js"
      category: "Framework"
      rating: 5
    - name: "Express.js"
      category: "Framework"
      rating: 4
    - name: "Django"
      category: "Framework"
      rating: 4
    - name: "Next.js"
      category: "Framework"
      rating: 4
    - name: "PostgreSQL"
      category: "Datastore"
      rating: 5
    - name: "Redis"
      category: "Datastore"
      rating: 4
    - name: "MongoDB"
      category: "Datastore"
      rating: 3
    - name: "Kafka"
      category: "Datastore"
      rating: 4
    - name: "Docker"
      category: "Tools"
      rating: 5
    - name: "Kubernetes"
      category: "Tools"
      rating: 4
    - name: "Git"
      category: "Tools"
      rating: 5
    - name: "AWS"
      category: "Tools"
      rating: 4
    - name: "GCP"
      category: "Tools"
      rating: 3
    - name: "CI/CD"
      category: "Tools"
      rating: 4
    - name: "System Design"
      category: "Tools"
      rating: 4
    - name: "Observability"
      category: "Tools"
      rating: 4
    - name: "Distributed Systems"
      category: "Tools"
      rating: 4
    - name: "Event Driven"
      category: "Tools"
      rating: 4

experience:
  - company: "Postman"
    position: "Senior Engineer"
    duration: "2025 - Present"
    location: "Hyderabad, India"
    logo: "https://voyager.postman.com/logo/postman-logo-orange-stacked.svg"
    description: "Leading development of Postman's core API platform and developer tools. Working on scalable microservices architecture and improving developer experience for millions of users."
    achievements:
      - "Led the redesign of Postman's API documentation system"
      - "Improved API response times by 40% through optimization"
      - "Mentored 3 junior developers and conducted technical interviews"
    technologies: ["Node.js", "React", "TypeScript", "PostgreSQL", "Redis", "AWS"]

  - company: "HackerRank"
    position: "Senior Software Engineer"
    duration: "2023 - 2025"
    location: "Remote"
    logo: "https://cdn.prod.website-files.com/66b6d7fd4d3e9cef94717176/670ee06a416476e6459b791a_LogoDark.svg"
    description: "Developed and maintained HackerRank's assessment platform, focusing on code execution engine and candidate experience."
    achievements:
      - "Built a scalable code execution engine supporting 50+ programming languages"
      - "Reduced platform downtime by 60% through infrastructure improvements"
      - "Implemented real-time collaboration features for coding interviews"
    technologies: ["Python", "Django", "JavaScript", "Docker", "Kubernetes", "Redis"]

  - company: "HackerRank"
    position: "Software Engineer 2"
    duration: "2022 - 2023"
    location: "Remote"
    logo: "https://cdn.prod.website-files.com/66b6d7fd4d3e9cef94717176/670ee06a416476e6459b791a_LogoDark.svg"
    description: "Developed and maintained HackerRank's assessment platform, focusing on code execution engine and candidate experience."
    achievements:
      - "Built a scalable code execution engine supporting 50+ programming languages"
      - "Reduced platform downtime by 60% through infrastructure improvements"
      - "Implemented real-time collaboration features for coding interviews"
    technologies: ["Python", "Django", "JavaScript", "Docker", "Kubernetes", "Redis"]

  - company: "BrowserStack"
    position: "Software Engineer"
    duration: "2020 - 2021"
    location: "Mumbai, India"
    logo: "/companies/browserstack.svg"
    description: "Worked on BrowserStack's automated testing platform, developing tools for cross-browser testing and mobile app testing."
    achievements:
      - "Developed automated testing frameworks for mobile applications"
      - "Created browser automation tools used by 50,000+ developers"
      - "Optimized test execution pipeline reducing time by 30%"
    technologies: ["JavaScript", "Selenium", "Appium", "Node.js", "MongoDB"]

projects:
  - name: "DevTools Hub"
    description: "A comprehensive collection of developer tools and utilities built with React and Node.js. Features include API testing, code formatting, and database management tools."
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/show_page.png"
    github: "https://github.com/VAIBHAV7500/devtools-hub"
    technologies: ["React", "Node.js", "TypeScript", "PostgreSQL"]
    featured: true

  - name: "CodeCollab"
    description: "Real-time collaborative code editor with syntax highlighting, version control integration, and team collaboration features."
    image: "/projects/codecollab.png"
    github: "https://github.com/VAIBHAV7500/codecollab"
    technologies: ["React", "Socket.io", "Monaco Editor", "Express"]
    featured: true

  - name: "API Analytics Dashboard"
    description: "Comprehensive analytics platform for API monitoring, performance tracking, and developer insights."
    image: "/projects/api-analytics.png"
    github: "https://github.com/VAIBHAV7500/api-analytics"
    technologies: ["Next.js", "D3.js", "PostgreSQL", "Redis"]
    featured: false

  - name: "TaskFlow"
    description: "Project management tool with kanban boards, time tracking, and team collaboration features."
    image: "/projects/taskflow.png"
    github: "https://github.com/VAIBHAV7500/taskflow"
    technologies: ["React", "Node.js", "MongoDB", "Socket.io"]
    featured: false

blogs:
  - title: "Building Scalable Microservices with Node.js"
    excerpt: "Learn how to design and implement scalable microservices architecture using Node.js, Docker, and Kubernetes."
    date: "2024-01-15"
    readTime: "8 min read"
    tags: ["Node.js", "Microservices", "Architecture"]
    url: "https://blog.vaibhavsolanki.dev/scalable-microservices-nodejs"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/cover.png"

  - title: "Optimizing React Performance: A Deep Dive"
    excerpt: "Advanced techniques for optimizing React applications, including code splitting, memoization, and bundle optimization."
    date: "2023-12-20"
    readTime: "12 min read"
    tags: ["React", "Performance", "JavaScript"]
    url: "https://blog.vaibhavsolanki.dev/react-performance-optimization"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/show_page.png"

  - title: "API Design Best Practices for Developer Experience"
    excerpt: "Comprehensive guide to designing APIs that developers love to use, covering REST, GraphQL, and documentation."
    date: "2023-11-10"
    readTime: "10 min read"
    tags: ["API Design", "GraphQL", "Developer Experience"]
    url: "https://blog.vaibhavsolanki.dev/api-design-best-practices"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/show_page.png"

  - title: "The Future of Developer Tools"
    excerpt: "Exploring emerging trends in developer tools and how AI is transforming the development workflow."
    date: "2023-10-05"
    readTime: "6 min read"
    tags: ["Developer Tools", "AI", "Future"]
    url: "https://blog.vaibhavsolanki.dev/future-developer-tools"
    #image: "/blogs/future-dev-tools.png"

contact:
  email: "vbhvsolanki7500@gmail.com"
  linkedin: "https://linkedin.com/in/vaibhav.solanki"
  github: "https://github.com/VAIBHAV7500"
  #twitter: "https://twitter.com/vaibhavsolanki"
  resume: "/resume.pdf" 
  instagram: "https://www.instagram.com/vbhvsolanki"
  formAccessKey: "9a9ccd91-f1c0-4e46-afc3-782974d579c3"