personal:
  name: "Vaibhav Solanki"
  title: "Senior Software Engineer"
  company: "Postman"
  location: "Bangalore, India"
  email: "vbhvsolanki7500@gmail.com"
  github: "https://github.com/VAIBHAV7500"
  linkedin: "https://linkedin.com/in/vaibhav.solanki"
  #twitter: "https://twitter.com/vaibhavsolanki"
  instagram: "https://www.instagram.com/vbhvsolanki"
  avatar: "/avatar.png"
  images:
    - src: "/personal/photo1.png"
      caption: "Meet my personal therapist"
    - src: "/personal/photo2.png"
      caption: "A gourdeous day I guess"
    - src: "/personal/photo3.png"
      caption: "Finding Nemo!"

about:
  summary: "I'm a Senior Software Engineer with 5+ years of experience building scalable web applications and developer tools. Currently working at Postman, I've previously contributed to platforms like HackerRank and BrowserStack."
  description: "Hellooo 👋\n\nHappy to see you here!\nI am Vaibhav, a Software Engineer with a passion for building innovative products. My journey in technology is fueled by a love for problem-solving and creating impactful solutions. Beyond coding, I am a big fan of anime and manga, which inspire my creativity. I also love traveling and exploring new places, as each adventure enriches my perspective and fuels my passion for discovery.\n Have a nice day!\n\nBest Vaibhav"
  skills:
  - name: "Golang"
    category: "Languages"
    rating: 5
  - name: "Python"
    category: "Languages"
    rating: 5
  - name: "JavaScript"
    category: "Languages"
    rating: 5
  - name: "TypeScript"
    category: "Languages"
    rating: 4
  - name: "SQL"
    category: "Languages"
    rating: 5

  - name: "React"
    category: "Web Development"
    rating: 3
  - name: "Next.js"
    category: "Web Development"
    rating: 4
  - name: "Node.js"
    category: "Web Development"
    rating: 5
  - name: "Express.js"
    category: "Web Development"
    rating: 5

  - name: "PostgreSQL"
    category: "DB & Messaging"
    rating: 5
  - name: "Redis"
    category: "DB & Messaging"
    rating: 5
  - name: "MongoDB"
    category: "DB & Messaging"
    rating: 4
  - name: "Kafka"
    category: "DB & Messaging"
    rating: 5

  - name: "Docker"
    category: "DevOps"
    rating: 5
  - name: "Kubernetes"
    category: "DevOps"
    rating: 4
  - name: "Git"
    category: "DevOps"
    rating: 5
  - name: "CI/CD"
    category: "DevOps"
    rating: 4
  - name: "Observability"
    category: "DevOps"
    rating: 5

  - name: "AWS"
    category: "DevOps"
    rating: 5
  - name: "GCP"
    category: "DevOps"
    rating: 3

  - name: "System Design"
    category: "Architecture"
    rating: 5
  - name: "Distributed Systems"
    category: "Architecture"
    rating: 5
  - name: "Event Driven"
    category: "Architecture"
    rating: 4

experience:
  - company: "Postman"
    position: "Senior Engineer"
    duration: "2025 - Present"
    location: "Hyderabad, India"
    logo: "https://voyager.postman.com/logo/postman-logo-orange-stacked.svg"
    description: "Built and maintained Postman’s Authentication System to ensure secure and reliable user access across the platform."
    achievements:
      - "Building and maintaining Postman's Authentication System"
    technologies: ["Javascript", "MySQL", "Redis", "AWS"]

  - company: "HackerRank"
    position: "Senior Software Engineer"
    duration: "2023 - 2025"
    location: "Remote"
    logo: "https://cdn.prod.website-files.com/66b6d7fd4d3e9cef94717176/670ee06a416476e6459b791a_LogoDark.svg"
    description: "Built scalable backend services, integrated SAML/SSO, and optimized database performance to improve reliability and user experience."
    achievements:
      - "Developed a high-performance, scalable Authorization Service from the ground up, supporting 1M RPM and stress-tested to 60M RPM. Improved system security, stability, and resource allocation"
      - "Integrated SAML and SSO flows into a newly developed authentication service, enhancing user accessibility and security compliance for enterprise clients."
      - "Built a robust, fault-tolerant Orchestra Service capable of processing over 50k events per second, ensuring reliable event handling at scale."
      - "Identified and resolved slow database queries in the monolithic application, reducing DB load by 50% and significantly enhancing response times and user experience"
    technologies: ["Golang", "Zanzibar", "Temporal", "MySQL", "AWS", "Kubernetes", "Docker"]

  - company: "HackerRank"
    position: "Software Engineer 2"
    duration: "2022 - 2023"
    location: "Remote"
    logo: "https://cdn.prod.website-files.com/66b6d7fd4d3e9cef94717176/670ee06a416476e6459b791a_LogoDark.svg"
    description: "Automated infrastructure workflows to reduce deployment time, scale VM provisioning to 300k+ daily, and enhance environment reliability through in-VM monitoring and analytics."
    achievements:
      - "Reduced machine image deployment time by 99.65%, from 1 day to 5 minutes, through end-to-end automation, significantly improving operational efficiency and resource allocation"
      - "Developed an automated pre-demand scaling solution, enabling the daily launch of over 300k virtual machines without breaching cloud provider quotas, ensuring seamless test environment provisioning."
      - "Built an in-VM system process to continuously monitor IDE and VM health, perform security checks, and export data for analytics, enhancing environment reliability and providing actionable insights."
    technologies: ["Golang", "Hashicorp", "Kubernetes", "Docker", "Grafana", "Prometheus", "AWS", "GCP"]

  - company: "BrowserStack"
    position: "Software Engineer"
    duration: "2020 - 2021"
    location: "Mumbai, India"
    logo: "/companies/browserstack.svg"
    description: "Led major system upgrades, optimized order workflows, automated sales processes with DocuSign, and migrated contract management to Salesforce for improved efficiency and consistency."
    achievements:
      - "Led the upgrade of Ruby (from 2.2.x to 2.6.x) and Rails (from 4.x to 6.x) across the entire product, achieving an 8% improvement in memory management and a 10% boost in CPU performance, enhancing overall system efficiency."
      - "Streamlined the order cancellation architecture and introduced functionality for managing future-dated orders, reducing operational workload by 20% and increasing workflow efficiency."
      - "Improved quote creation and invoice generation by integrating DocuSign, automating the handling of sales orders, and accelerating the sales opportunity closure process."
      - "Migrated contract lifecycle management to Salesforce, moving away from Google Drive-based storage, improving accessibility and process consistency."
    technologies: ["Ruby", "Rails", "PostgreSQL", "AWS", "Docker", "Kubernetes", "GCP"]

projects:
  - name: "Anime Web App"
    description: "A self designed anime web app with a modern UI and a clean design."
    image: "/projects/loading_4.svg"
    github: "https://github.com/VAIBHAV7500/anime_web_app"
    technologies: ["React", "Node.js", "MySQL", "Redis", "Docker", "AWS"]
    featured: true

  - name: "Let's Binge"
    description: "A Video Platform which allows user to watch videos in Sync and Chat. "
    image: "/projects/letsbinge.svg"
    github: "https://github.com/VAIBHAV7500/lets_binge"
    technologies: ["React", "Firestore"]
    featured: true

blogs:
  - title: "Building Scalable Microservices with Node.js"
    excerpt: "Learn how to design and implement scalable microservices architecture using Node.js, Docker, and Kubernetes."
    date: "2024-01-15"
    readTime: "8 min read"
    tags: ["Node.js", "Microservices", "Architecture"]
    url: "https://blog.vaibhavsolanki.dev/scalable-microservices-nodejs"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/cover.png"

  - title: "Optimizing React Performance: A Deep Dive"
    excerpt: "Advanced techniques for optimizing React applications, including code splitting, memoization, and bundle optimization."
    date: "2023-12-20"
    readTime: "12 min read"
    tags: ["React", "Performance", "JavaScript"]
    url: "https://blog.vaibhavsolanki.dev/react-performance-optimization"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/show_page.png"

  - title: "API Design Best Practices for Developer Experience"
    excerpt: "Comprehensive guide to designing APIs that developers love to use, covering REST, GraphQL, and documentation."
    date: "2023-11-10"
    readTime: "10 min read"
    tags: ["API Design", "GraphQL", "Developer Experience"]
    url: "https://blog.vaibhavsolanki.dev/api-design-best-practices"
    image: "https://raw.githubusercontent.com/VAIBHAV7500/anime_web_app/master/images/show_page.png"

  - title: "The Future of Developer Tools"
    excerpt: "Exploring emerging trends in developer tools and how AI is transforming the development workflow."
    date: "2023-10-05"
    readTime: "6 min read"
    tags: ["Developer Tools", "AI", "Future"]
    url: "https://blog.vaibhavsolanki.dev/future-developer-tools"
    #image: "/blogs/future-dev-tools.png"

contact:
  email: "vbhvsolanki7500@gmail.com"
  linkedin: "https://linkedin.com/in/vaibhav.solanki"
  github: "https://github.com/VAIBHAV7500"
  #twitter: "https://twitter.com/vaibhavsolanki"
  resume: "/personal/resume.pdf" 
  instagram: "https://www.instagram.com/vbhvsolanki"
  messagePlaceholder: "Write your message here..."
  subjectPlaceholder: "What's this about?"